### ISSUE TITLE
KDE Connect system tray issue

### ISSUE THREAD

**Issue by Nocxium** [scorpion-26/gBar#38] opened 2023-08-22 16:07 UTC
Hi
For some reason i get this error whenever i have KDE conenct / Indicator in the systray, and the bar becomes buggy with alot of flickering and the icons dissapearing:

(gBar:81868): Gtk-CRITICAL **: 18:03:26.139: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
SNI: Add :1.10 to widget

(gBar:81868): GdkPixbuf-CRITICAL **: 18:03:26.139: gdk_pixbuf_new_from_bytes: assertion 'height > 0' failed
SNI: Add :1.20 to widget

(gBar:81868): GdkPixbuf-CRITICAL **: 18:03:26.151: gdk_pixbuf_get_n_channels: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(gBar:81868): GdkPixbuf-CRITICAL **: 18:03:26.151: gdk_pixbuf_get_height: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(gBar:81868): GdkPixbuf-CRITICAL **: 18:03:26.151: gdk_pixbuf_get_width: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

(gBar:81868): Gtk-WARNING **: 18:03:26.151: drawing failure for widget 'GtkDrawingArea': invalid matrix (not invertible)

(gBar:81868): Gtk-WARNING **: 18:03:26.151: drawing failure for widget 'GtkEventBox': invalid matrix (not invertible)

(gBar:81868): Gtk-WARNING **: 18:03:26.151: drawing failure for widget 'GtkBox': invalid matrix (not invertible)

(gBar:81868): Gtk-WARNING **: 18:03:26.151: drawing failure for widget 'GtkBox': invalid matrix (not invertible)

(gBar:81868): Gtk-WARNING **: 18:03:26.151: drawing failure for widget 'GtkBox': invalid matrix (not invertible)

(gBar:81868): Gtk-WARNING **: 18:03:26.151: drawing failure for widget 'GtkBox': invalid matrix (not invertible)

(gBar:81868): Gtk-WARNING **: 18:03:26.151: drawing failure for widget 'GtkWindow': invalid matrix (not invertible)

Im using Hyprland on NixOS

**Comment by scorpion-26** [comment] 2023-08-22 20:50
The crash should be fixed with the linked commit. Please note, that the icon won't show up as of now, since gBar currently doesn't support svg yet. I'll probably implement that soon though.

**Comment by Nocxium** [comment] 2023-08-22 23:10
Thanks a lot for the quick fix :)
One thing i find strange though is that previously my webcord icon showed up in systray, but not anymore after the commit... any ideas why? This is my output:

(gBar:4619): Gtk-CRITICAL **: 01:08:28.471: gtk_widget_set_visible: assertion 'GTK_IS_WIDGET (widget)' failed

(gBar:4619): Gtk-CRITICAL **: 01:08:28.472: gtk_range_set_value: assertion 'GTK_IS_RANGE (range)' failed
sh: line 1: checkupdates: command not found
GetOutdatedPackages: Invalid command. Disabling package widget!
SNI: Registered Item :1.10 /StatusNotifierItem
SNI: Creating Item :1.10 /StatusNotifierItem
SNI: Searching icon kdeconnectindicatordark in /nix/store/macbdimi9sxmmv76ajbcin22bf800481-desktops/share/icons
SNI: Searching icon kdeconnectindicatordark in /home/ozz/.nix-profile/share/icons
SNI: Searching icon kdeconnectindicatordark in /etc/profiles/per-user/ozz/share/icons
SNI: Searching icon kdeconnectindicatordark in /nix/var/nix/profiles/default/share/icons
SNI: Searching icon kdeconnectindicatordark in /run/current-system/sw/share/icons
SNI: Searching icon kdeconnectindicatordark in /usr/share/icons
SNI: Cannot find icon path for :1.10
SNI: Clearing old children
Destroy widget

(gBar:4619): Gtk-CRITICAL **: 01:08:29.500: gtk_widget_destroy: assertion 'GTK_IS_WIDGET (widget)' failed
SNI: Lost Name! Disabling SNI!
SNI: Lost Name! Disabling SNI!
^C%                         

And thanks for an awesome status bar :)

**Comment by scorpion-26** [comment] 2023-08-23 13:27
Do you have another bar (or two gBar instances) with systray support open by chance? ```SNI: Lost Name! Disabling SNI!``` should mean, that another bar has overriden the systray, since gBar currently doesn't play nicely with multiple systrays open simultaneously. Anyways, a restart should fix it, otherwise please open another issue (You may need to also restart WebCord *after* restarting gBar). Closing, because the original issue was fixed.

**Closed by scorpion-26** 2023-08-23 13:27 UTC

**Comment by scorpion-26** [comment] 2023-08-23 21:29
> One thing i find strange though is that previously my webcord icon showed up in systray, but not anymore after the commit... any ideas why?

I just found a regression with the fix, which caused some of the icons to never appear. Should be fixed now (383f25d)
