### ISSUE TITLE
System tray menus are not always showing and blocking the keyboard input

### ISSUE THREAD

**Issue by fdev31** [scorpion-26/gBar#79] opened 2024-03-17 18:07 UTC
using "nm-applet" or another system tray icon, I can briefly see a menu (with a lot of extra/unneeded padding at the bottom).
Most of the time the content of the menu disappears after a short duration and the keyboard input is blocked (everything but Hyprland's shortcuts) until I kill gBar.

The console shows repeated errors:

```
(gBar:135125): Gtk-CRITICAL **: 19:04:11.240: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for WidgetsCenter: [Title]
(gBar:135125): Gtk-CRITICAL **: 19:04:11.247: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for CPUThermalZone: /sys/devices/pci0000:00/0000:00:18.3/hwmon/hwmon2/temp1_input
(gBar:135125): Gtk-CRITICAL **: 19:04:11.254: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for ExitCommand: killall Hyprland
(gBar:135125): Gtk-CRITICAL **: 19:04:11.261: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for DiskPartition: /
(gBar:135125): Gtk-CRITICAL **: 19:04:11.268: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for WorkspaceSymbol: 3,
(gBar:135125): Gtk-CRITICAL **: 19:04:11.275: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for WorkspaceSymbol: 6,
(gBar:135125): Gtk-CRITICAL **: 19:04:11.345: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for WorkspaceSymbol: 9,亮
(gBar:135125): Gtk-CRITICAL **: 19:04:11.352: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for ShutdownIcon: \s
(gBar:135125): Gtk-CRITICAL **: 19:04:11.359: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for LockIcon: 
(gBar:135125): Gtk-CRITICAL **: 19:04:11.366: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for BTOnIcon: 󰂯
(gBar:135125): Gtk-CRITICAL **: 19:04:11.373: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for DevMouseIcon: 󰍽\s
(gBar:135125): Gtk-CRITICAL **: 19:04:11.387: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for DevUnknownIcon: \s
(gBar:135125): Gtk-CRITICAL **: 19:04:11.394: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for MicMutedIcon: 󰍭
(gBar:135125): Gtk-CRITICAL **: 19:04:11.401: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for WorkspaceScrollOnMonitor: true
(gBar:135125): Gtk-CRITICAL **: 19:04:11.415: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for UseHyprlandIPC: true
(gBar:135125): Gtk-CRITICAL **: 19:04:11.422: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for CenterTime: false
(gBar:135125): Gtk-CRITICAL **: 19:04:11.429: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for TimeSpace: 30
(gBar:135125): Gtk-CRITICAL **: 19:04:11.436: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for DateTimeStyle: %a %d/%m %H:%M
(gBar:135125): Gtk-CRITICAL **: 19:04:11.443: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for AudioScrollSpeed: 1
(gBar:135125): Gtk-CRITICAL **: 19:04:11.450: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed                                                                   then exit 127; fi; if [ $e -eq 2 ] 
; then echo "0" && exit 0; fi; echo "$p" | wc -l
(gBar:135125): Gtk-CRITICAL **: 19:04:11.457: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for NetworkWidget: true
(gBar:135125): Gtk-CRITICAL **: 19:04:11.464: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for SensorSize: 16
(gBar:135125): Gtk-CRITICAL **: 19:04:11.471: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for EnableSNI: true
(gBar:135125): Gtk-CRITICAL **: 19:04:11.478: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Set value for MinUploadBytes: 0
(gBar:135125): Gtk-CRITICAL **: 19:04:11.485: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
Wayland: Monitor at ID 0 got name eDP-1
(gBar:135125): Gtk-CRITICAL **: 19:04:11.492: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
PulseAudio: Update info
(gBar:135125): Gtk-CRITICAL **: 19:04:11.499: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Clearing old children
(gBar:135125): Gtk-CRITICAL **: 19:04:11.506: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Registered Item :1.970 /org/ayatana/NotificationItem/nm_applet
(gBar:135125): Gtk-CRITICAL **: 19:04:11.513: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Title: Bluetooth activé
(gBar:135125): Gtk-CRITICAL **: 19:04:11.520: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Allocating static name buffer for :1.2194
(gBar:135125): Gtk-CRITICAL **: 19:04:11.527: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Creating icon from "nm-signal-75-secure"
(gBar:135125): Gtk-CRITICAL **: 19:04:11.534: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Menu object path: /org/ayatana/NotificationItem/gammastep/Menu
(gBar:135125): Gtk-CRITICAL **: 19:04:11.541: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Clearing old children
(gBar:135125): Gtk-CRITICAL **: 19:04:11.549: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Creating Item :1.970 /org/ayatana/NotificationItem/nm_applet
SNI: Menu object path: /org/ayatana/NotificationItem/nm_applet/Menu
SNI: Creating icon from "nm-signal-75-secure"
SNI: Allocating static name buffer for :1.970
SNI: Clearing old children
Remove widget from parent
SNI: Add :1.2201 to widget
SNI: Add :1.968 to widget
SNI: Add :1.970 to widget
SNI: Clearing old children
(gBar:135125): Gtk-CRITICAL **: 19:04:11.946: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Add :1.968 to widget
(gBar:135125): Gtk-CRITICAL **: 19:04:11.953: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
(gBar:132615): LIBDBUSMENU-GLIB-CRITICAL **: 19:00:01.583: dbusmenu_menuitem_send_about_to_show: assertion 'DBUSMENU_I
(gBar:135125): Gtk-CRITICAL **: 19:04:11.960: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Reloading :1.970 /org/ayatana/NotificationItem/nm_applet (Sender: :1.970)
(gBar:135125): Gtk-CRITICAL **: 19:04:11.968: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
(gBar:132615): Gtk-CRITICAL **: 19:00:02.252: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget
(gBar:135125): Gtk-CRITICAL **: 19:04:11.974: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
(gBar:132615): Gtk-CRITICAL **: 19:00:02.252: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget
(gBar:135125): Gtk-CRITICAL **: 19:04:11.981: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:11.988: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:11.995: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.003: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.010: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.016: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.023: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Creating Item :1.970 /org/ayatana/NotificationItem/nm_applet
(gBar:135125): Gtk-CRITICAL **: 19:04:12.030: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Allocating static name buffer for :1.970
(gBar:135125): Gtk-CRITICAL **: 19:04:12.037: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Add :1.2194 to widget
(gBar:135125): Gtk-CRITICAL **: 19:04:12.044: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.051: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.058: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.065: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.072: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.079: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.086: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.093: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.100: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.107: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.114: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.121: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.128: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.135: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.142: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.149: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.156: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.163: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.170: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.177: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.184: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.590: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.597: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.604: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.611: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.618: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.625: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.632: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.639: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

(gBar:135125): Gtk-CRITICAL **: 19:04:12.646: _gtk_widget_captured_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed
SNI: Reloading :1.970 /org/ayatana/NotificationItem/nm_applet (Sender: :1.970)
SNI: Actual object path: /org/ayatana/NotificationItem/nm_applet
SNI: Delete static name buffer for :1.970
SNI: Creating Item :1.970 /org/ayatana/NotificationItem/nm_applet
SNI: Menu object path: /org/ayatana/NotificationItem/nm_applet/Menu
SNI: Creating icon from "nm-signal-75-secure"
SNI: Allocating static name buffer for :1.970
SNI: Clearing old children
Remove widget from parent
SNI: Add :1.2201 to widget
SNI: Add :1.968 to widget
SNI: Add :1.970 to widget
zsh: terminated  gBar bar eDP-1
```

**Comment by scorpion-26** [comment] 2024-03-18 01:45
Should be fixed now. 

> with a lot of extra/unneeded padding at the bottom

This was actually a long time known bug of the SNI implementation. While fixing this bug I managed to find the cause of it by chance, so it should be good now. (You may need to update the ```.popup``` and ```menu``` selectors from the default css for things to look properly).

**Closed by scorpion-26** 2024-03-18 01:45 UTC
Labels: bug
